### ISSUE TITLE
Love your app

### ISSUE THREAD

**Issue by TheOddPortrait** [amzn/login-with-amazon-wordpress#2]
Hey there great work so far really enjoying it.

Question however, is there a way I can add it into my wordpress page say /my-account  you know where you go to login, or register, a button at the bottom that takes you directly to the login screen with amazon? here is an example.
https://www.reddressboutique.com/customer/account/login/  
see how they have it there at the bottom?
https://www.theoddportrait.com/my-account/

would want to add it down there, not sure if there is a shortcode , sorry newish to hope it was not answered elsewhere but thanks for the support !

**Comment by LetMyPeopleCode** [comment]
Hi TheOddPortrait,

The button is automatically inserted under the login form on the login page. Here's a screen cap of a fresh WordPress install running the default 2016 theme. 

Rather than a shortcode, it looks for a specific hook in the default login page. If it doesn't appear on your login page after install, I can help debug. Contact me directly at bulmashg [at] amazon.com.

![wp-login](https://cloud.githubusercontent.com/assets/10713246/17612436/a5dab440-6006-11e6-9038-151949342800.png)

**Comment by sklangoo** [comment]
Hi TheOddPortrait,
Closing the issue. Kindly let us know if you have any further questions.
Thanks.
